spring:
  application:
    name: pokemon--tcg-collector-backend
    version: '@project.version@'
  liquibase:
    change-log: liquibase/master.xml
    url: jdbc:postgresql://${POSTGRES_HOST}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  version: '@project.version@'
  show-actuator: true

api:
  pokemontcg:
    key: ${POKEMON_TCG_API_KEY}
    url: https://api.pokemontcg.io/v2
